### ISSUE TITLE
Not work under osx 

### ISSUE THREAD

**Issue by huan** [snowyu/node-nosql-leveldb#2]
Please fix, looking forward to make https://travis-ci.org/snowyu/node-nosql-leveldb/ green!

**Comment by snowyu** [comment]
Can compile above node v7 now. But It can not destroy iterator on Mac when exiting.

You can try your unit test.

**Comment by huan** [comment]
Thanks. Could you please publish the latest code to NPM?

Then I'll be able to test it in my project.

**Comment by snowyu** [comment]
Try this:

"dependencies" : {
  "nosql-leveldb" : "git://github.com/snowyu/node-nosql-leveldb.git"
}

**Comment by huan** [comment]
Bad news: it `Segmentation fault` again.

See: https://travis-ci.com/zixia/flash-store/jobs/131516727

I believe my ci will be able to turn green only after yours:

https://travis-ci.org/snowyu/node-nosql-leveldb/builds/397147351

**Comment by snowyu** [comment]
All tests passed on Mac. You can try it again now.

**Comment by huan** [comment]
Awesome, it passed.

Can you publish a new NPM version for now?

**Comment by snowyu** [comment]
Released 3.0.1.
